[tox]
envlist = build
skipsdist = True

[testenv:build]
allowlist_externals = 
    pyinstaller
    python
deps =
    build
    pyinstaller
    Pillow
commands =
    # Build wheel
    python -m build --wheel --outdir dist/
    # Create Windows Icon (if on windows)
    python -c "from PIL import Image; img = Image.open('src/comiccatcher/resources/app_256.png'); img.save('packaging/windows/comiccatcher.ico', format='ICO', sizes=[(16,16), (32,32), (48,48), (64,64), (128,128), (256,256)])"
    # Run PyInstaller
    python -m PyInstaller --noconfirm --windowed --onefile \
        --name "ComicCatcher" \
        --icon "packaging/windows/comiccatcher.ico" \
        --collect-all "comiccatcher" \
        --add-data "src/comiccatcher/resources{ossep}comiccatcher/resources" \
        "src/comiccatcher/main.py"
