#!/bin/bash
set -e

# Base directory for the project
BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$BASE_DIR"

BUILD_INFO_FILE="src/comiccatcher/_build_info.py"
INIT_FILE="src/comiccatcher/__init__.py"

echo "🔍 Generating build info..."
GIT_DESCRIBE=$(git describe --tags --always --dirty || echo "unknown")
GIT_HASH=$(git rev-parse --short HEAD || echo "unknown")

# PEP 440 local version identifiers allow alphanumeric characters and dots
if [ -z "$(git status --porcelain)" ]; then
    LOCAL_VER="g${GIT_HASH}"
else
    LOCAL_VER="g${GIT_HASH}.d"
fi

echo "Writing $GIT_DESCRIBE to $BUILD_INFO_FILE"
cat <<EOF > "$BUILD_INFO_FILE"
# Auto-generated by build_package.sh
__commit__ = "$GIT_DESCRIBE"
EOF

# Read the current version directly from __init__.py
BASE_VERSION=$(grep -oP '(?<=__version__ = ")[^"]+' "$INIT_FILE")

# If it's an alpha (a), beta (b), or release candidate (rc), append the local version tag
if [[ "$BASE_VERSION" =~ (a|b|rc)[0-9]+$ ]]; then
    PACKAGED_VERSION="${BASE_VERSION}+${LOCAL_VER}"
    echo "Pre-release version detected. Setting package version to $PACKAGED_VERSION"
    # Create a backup and replace the version inline
    sed -i.bak "s/__version__ = \"$BASE_VERSION\"/__version__ = \"$PACKAGED_VERSION\"/" "$INIT_FILE"
else
    echo "Standard release version detected: $BASE_VERSION"
fi

echo "📦 Building package..."
# Build the wheel and source distribution
python3 -m build

echo "🧹 Cleaning up..."
rm -f "$BUILD_INFO_FILE"

# Restore __init__.py if we modified it
if [ -f "${INIT_FILE}.bak" ]; then
    mv "${INIT_FILE}.bak" "$INIT_FILE"
fi

echo "✅ Build complete. Packages are in the 'dist' directory."